FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /CityApi
   
# copy source
COPY city.api/. .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /CityApi   
COPY --from=build /CityApi/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "city.api.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet city.api.dll

CMD ASPNETCORE_URLS=http://*:$PORT dotnet city.api.dll